apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  namespace: ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sujitha
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sujitha
    spec:
      containers:
        - name: sujitha-cont
          image: suryaa112003/sujitha-project:v1.1.0
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: sujitha-secret
                  key: MONGO_URI
            - name: PORT  
              valueFrom:
                configMapKeyRef:
                  name: sujitha-config
                  key: PORT
---
apiVersion: v1
kind: Service
metadata:
  name: sujitha-svc
  namespace: ns
spec:
  selector:
    app: sujitha
  ports:
    - port: 3001
      targetPort: 3000
  type: ClusterIP